/* ============================================================
   GUN DUEL 言語ファイル
   画面に出る文字はすべてここ。言語を増やすときは ja をまるごとコピーして訳すだけ。
   {name} のような部分は、表示するときに実際の値に置きかわる。
   ============================================================ */
(function (root) {
'use strict';
var ja = {
  'lang.name': '日本語',
  'common.back': '戻る',
  'common.backMenu': 'メニューに戻る',
  'common.save': '保存',
  'common.saved': '保存しました',
  'common.reset': '初期設定に戻す',
  'common.sound': 'サウンドON/OFF',
  'common.settings': '設定',
  'common.fullscreen': '全画面表示',

  'tos.kicker': 'Terms of Service',
  'tos.title': 'GUN DUEL 利用規約',
  'tos.h1': '禁止事項',
  'tos.h1.li1': 'チート・改造クライアント・オートエイム／エイムボット・BOT操作など、不正なプログラムやツールの使用',
  'tos.h1.li2': 'ゲームやサーバーの脆弱性を意図的に悪用する行為',
  'tos.h1.li3': '他のプレイヤーへの嫌がらせ・迷惑行為',
  'tos.h2': '違反した場合',
  'tos.h2.li1': '警告なしでアカウント・戦績（プロフィール／ティア）をリセットする場合があります',
  'tos.h2.li2': '対戦への参加資格をはく奪（BAN）する場合があります',
  'tos.h2.li3': '違反内容によっては「罰金」（ペナルティ）が科される場合があります',
  'tos.h3': 'その他',
  'tos.h3.li1': '本規約は個人が開発したファンメイドの対戦ゲームに適用される簡易的なものです',
  'tos.h3.li2': 'サーバーの稼働状況や通信環境による切断・不具合について保証はできません',
  'tos.h3.li3': '内容は予告なく変更される場合があります',
  'tos.agree': '上記の利用規約に同意します',
  'tos.start': '同意してゲームを始める',

  'home.tagline': '14種類の武器から3つ選んで戦う、3本先取の対戦ゲーム',
  'home.barHint': 'プロフィールを見る・編集する',
  'menu.ai': 'AI対戦',
  'menu.ai.sub': 'ローカル動作・ラグなし',
  'menu.loadout': '武器セット',
  'menu.loadout.sub': '14種類から3つ選んで持っていく',
  'menu.online': 'オンライン対戦',
  'menu.online.sub': '友達と対戦（チート防止・低遅延）',
  'menu.profile': 'プロフィール',
  'menu.profile.sub': '見た目・称号・背景・戦績',
  'login.discord': 'Discordでログイン',
  'login.logout': 'ログアウト',
  'login.note': 'ログインすると、プロフィールがどの端末でも同じになり、フレンドも使えます',
  'login.record': 'オンライン {w}勝 {l}敗',
  'login.unavailable': 'このサーバーではログインが使えません',
  'login.canceled': 'ログインを中止しました',
  'login.stateError': 'ログインを確認できませんでした。もう一度お試しください。',
  'login.failed': 'ログインできませんでした',
  'login.banned': 'このアカウントは利用停止されています',
  'login.tooMany': '試行が多すぎます。しばらく待ってください',
  'login.noServer': 'サーバーに接続できませんでした',

  'stage.kicker': 'Stage Select',
  'stage.title': 'ステージ選択',
  'stage.sub': '戦う舞台を選ぼう',
  'stage.no': 'STAGE {n}',
  'stage.backMode': 'モード選択に戻る',
  'stage.classic.name': 'クラシック',
  'stage.classic.desc': '高さばらばらの木の足場。上を取って撃ち下ろせ',
  'stage.classic.theme': '月夜の西部の町',
  'stage.flat.name': 'フラット',
  'stage.flat.desc': '隠れる場所はない。雷鳴の中、真っ向勝負の読み合い',
  'stage.flat.theme': '嵐の大平原',
  'stage.tower.name': 'タワー',
  'stage.tower.desc': '中央の鉄塔を登れ。頂上は強いが、四方から狙われる',
  'stage.tower.theme': '摩天楼の鉄塔',
  'stage.ruins.name': '砂漠の遺跡',
  'stage.ruins.desc': '石柱が弾を止める。隠れて、のぞいて、撃ち返せ',
  'stage.ruins.theme': '夕暮れの砂漠遺跡',
  'stage.glacier.name': '氷の谷',
  'stage.glacier.desc': '谷に落ちたら即アウト。浮かぶ氷を跳び移れ',
  'stage.glacier.theme': '底なしの氷の谷',
  'stage.temple.name': '密林の神殿',
  'stage.temple.desc': '段差が弾を防ぐ。頂上からは戦場が見渡せる',
  'stage.temple.theme': '密林に眠る神殿',
  'stage.classic.tags': '足場が多い,高低差',
  'stage.flat.tags': '足場なし,地上戦',
  'stage.tower.tags': '中央の塔,高所が有利',
  'stage.ruins.tags': '遮蔽物,隠れて撃つ',
  'stage.glacier.tags': '落下あり,跳び移り',
  'stage.temple.tags': '段差,頂上争い',
  'stage.go': 'このステージで戦う',
  'stage.count': '{n} / {total}',
  'stage.keys': '← → で切り替え　Enter で決定',
  'stage.new': 'NEW',
  'vs.winrate': '勝率 {p}%',
  'vs.record': '{w}勝 {l}敗',
  'vs.online': 'オンライン',
  'vs.cpu': 'CPU戦',
  'vs.noRecord': '戦績なし',
  'vs.discord': 'Discord ✓ {name}',
  'menu.friends': 'フレンド',
  'menu.friends.sub': 'フレンドID・申請・対戦の招待',
  'fr.kicker': 'Friends',
  'fr.title': 'フレンド',
  'fr.needLogin': 'フレンド機能を使うには、Discord でログインしてください。',
  'fr.myId': 'あなたのフレンドID',
  'fr.addTitle': 'フレンドを追加',
  'fr.addPh': '相手のフレンドID（8文字）',
  'fr.add': '申請する',
  'fr.incoming': '届いた申請（{n}）',
  'fr.outgoing': '送った申請',
  'fr.list': 'フレンド（オンライン {on} / {n}人）',
  'fr.none': 'まだフレンドがいません。フレンドIDを教え合って申請しましょう',
  'fr.accept': '承認',
  'fr.decline': '拒否',
  'fr.cancel': '取り消す',
  'fr.waiting': '承認待ち',
  'fr.invite': '招待',
  'fr.remove': 'フレンド解除',
  'fr.removeConfirm': '{name} をフレンドから外しますか？',
  'fr.close': '閉じる',
  'fr.r.sent': '申請を送りました。相手が承認するとフレンドになります',
  'fr.r.accepted': '{name} とフレンドになりました',
  'fr.r.already': 'すでにフレンドです',
  'fr.r.pending': 'すでに申請しています',
  'fr.r.self': 'それはあなたのIDです',
  'fr.r.limit': 'フレンドの上限（100人）に達しています',
  'fr.r.full': '申請がいっぱいです。しばらく待ってください',
  'fr.r.not_found': 'そのIDのプレイヤーは見つかりません',
  'fr.r.bad': 'フレンドIDは英数字8文字です',
  'fr.r.error': '通信できませんでした。もう一度お試しください',
  'fr.r.too_many': '操作が多すぎます。少し待ってください',
  'fr.r.ok': '完了しました',
  'fr.gotRequest': '{name} からフレンド申請が届きました',
  'fr.notConnected': 'サーバーにつながっていません。少し待ってからお試しください',
  'fst.online': 'オンライン',
  'fst.cpu': 'CPU対戦中',
  'fst.match': '対戦中',
  'fst.offline': 'オフライン',
  'fst.offAgo': 'オフライン・{ago}',
  'ago.now': 'たった今',
  'ago.min': '{n}分前',
  'ago.hour': '{n}時間前',
  'ago.day': '{n}日前',
  'fm.tier': 'ティア',
  'fm.online': 'オンライン戦績',
  'fm.cpu': 'CPU戦績',
  'fm.discord': 'Discord',
  'fm.rec': '{w}勝 {l}敗・勝率 {p}%',
  'fm.noRec': '戦績なし',
  'inv.title': '対戦の招待',
  'inv.msg': 'から対戦の招待が届きました',
  'inv.join': '参加する',
  'inv.no': '断る',
  'inv.creating': '{name} を招待する部屋を作っています…',
  'inv.sending': '{name} に招待を送っています…',
  'inv.sent': '{name} に招待を送りました。返事を待っています…',
  'inv.sentCpu': '{name} はCPU対戦中です。試合が終わると招待が表示されます…',
  'inv.accepted': '{name} が参加します！',
  'inv.declined': '{name} に断られました',
  'inv.noAnswer': '{name} から返事がありませんでした',
  'inv.canceled': '{name} からの招待は取り消されました',
  'inv.fail.not_friend': 'フレンドではないため招待できません',
  'inv.fail.offline': '{name} はオフラインです',
  'inv.fail.busy': '{name} は対戦中です',
  'inv.fail.no_room': '部屋を作れませんでした。もう一度お試しください',
  'inv.fail.too_many': '招待が多すぎます。少し待ってください',
  'bot.notFound': '「{q}」というプレイヤーは見つかりませんでした。ゲーム内の名前・Discordの名前・フレンドID（8文字）で探せます（Discordでログインしたことのある人だけ）',
  'bot.many': '「{q}」に当てはまるプレイヤーが {n} 人います。フレンドIDで指定してください',
  'bot.tier': 'ティア',
  'bot.title': '二つ名',
  'bot.status': '状態',
  'bot.online': 'オンライン戦績',
  'bot.cpu': 'CPU戦績',
  'bot.fid': 'フレンドID',
  'bot.rec': '勝率 {p}%（{w}勝 {l}敗）',
  'bot.noRec': 'まだありません',
  'bot.lastSeen': '最後にいたのは {t}',

  'cpu.kicker': 'CPU Level',
  'cpu.title': 'CPUレベル選択',
  'cpu.sub': '移動・ジャンプ・リロードはどのレベルもプレイヤーと同じ。違うのは判断の速さと正確さだけ',
  'cpu.stage': 'ステージ：{name}',
  'cpu.weapons': '武器：{list}',
  'cpu.change': '武器を変える',
  'cpu.backStage': 'ステージ選択に戻る',
  'cpu.desc.easy': '判断はゆっくりだが動きは互角',
  'cpu.desc.normal': '反応が速く、弾もよく避ける',
  'cpu.desc.hard': '距離を保ちながら撃ち合ってくる',
  'cpu.desc.pro': '隠れて・避けて・隙を逃さない',
  'cpu.desc.god': '反応も判断も人間離れ',
  'diff.easy': 'よわい',
  'diff.normal': 'ふつう',
  'diff.hard': 'つよい',
  'diff.pro': '鬼',
  'diff.god': '鬼神',

  'room.kicker': 'Online Match',
  'room.title': 'オンライン対戦',
  'room.host': '部屋を作る',
  'room.create': '部屋を作って番号を表示する',
  'room.guest': '部屋に入る',
  'room.placeholder': '6桁の部屋番号を入力',
  'room.join': '入室する',
  'room.connecting': 'サーバーに接続中...',
  'room.waiting': '相手の入室を待っています...',
  'room.joined': '接続成功！',
  'room.connectFail': '接続失敗。サーバーURLを確認してください。',
  'room.need6': '6桁の番号を入力してください',
  'room.oldServer': 'サーバーが古いバージョンです。サーバー側のファイルも更新してください。',
  'room.error': 'エラー: {msg}',
  'err.login_required': 'オンライン対戦にはDiscordログインが必要です',
  'err.server_busy': 'サーバーが混み合っています。少し待ってからお試しください',
  'err.too_many_rooms': '同時に作れる部屋の数を超えています',
  'err.too_many_fails': '部屋番号の入力ミスが多すぎます。しばらく待ってからお試しください',
  'err.room_not_found': '部屋が見つかりません。番号を確認してください',
  'err.same_account': '同じアカウント同士では対戦できません',
  'err.room_full': 'この部屋はすでに対戦中です',
  'err.room_timeout': '相手が来なかったため部屋を閉じました',
  'err.reload': 'ゲームが更新されました。ページを再読み込みしてください',

  'set.kicker': 'Settings',
  'set.title': '設定',
  'set.sound': 'サウンド',
  'set.bgm': 'BGM',
  'set.se': '効果音',
  'set.lang': '言語',
  'set.keys': 'キーバインド',
  'set.server': 'サーバー',
  'set.serverNote': 'ふだんは変えなくて大丈夫です（自分でサーバーを動かすときだけ）',
  'kb.left': '左に移動',
  'kb.right': '右に移動',
  'kb.jump': 'ジャンプ',
  'kb.duck': 'しゃがむ',
  'kb.attack': '攻撃（押しっぱなしで撃ち続ける）',
  'kb.reload': 'リロード',
  'kb.w1': '武器スロット①',
  'kb.w2': '武器スロット②',
  'kb.w3': '武器スロット③',
  'kb.heal': '回復（1ラウンド1回）',
  'kb.waiting': '入力待ち...',
  'kb.unset': '未設定',
  'key.mouse0': '左クリック',
  'key.mouse1': '中クリック',
  'key.mouse2': '右クリック',

  'lo.kicker': 'Loadout',
  'lo.title': '武器セット',
  'lo.sub': '対戦に持っていく武器を3つ選ぼう。対戦中は 1・2・3 キーで持ち替え',
  'lo.hint': '変えたい枠を選んでから、下の武器を押す（すでに持っている武器は入れ替わる）',
  'lo.slot': 'SLOT {n}',
  'lo.start': '開始時',
  'lo.done': '決定して戻る',
  'st.range': '射程',
  'st.power': '威力',
  'st.rate': '連射',
  'st.mag': '弾数',
  'st.reload': 'リロード',
  'st.perSec': '{n}/秒',
  'st.sec': '{n}秒',
  'st.none': 'なし',
  'st.approx': '約{n}',

  'w.1.name': 'ナイフ', 'w.1.short': 'ナイフ', 'w.1.desc': '近づいて斬る。当たれば強いが、届く距離はとても短い',
  'w.2.name': 'ピストル', 'w.2.short': 'ピストル', 'w.2.desc': '1発ずつ撃つ基本の銃。撃つたびに短いリロード',
  'w.3.name': 'スナイパー', 'w.3.short': 'スナイパー', 'w.3.desc': '弾が速く遠くまで届く。撃つたびに長いリロード',
  'w.4.name': 'サブマシンガン', 'w.4.short': 'SMG', 'w.4.desc': '押しっぱなしで高速連射。近い距離で弾をばらまく',
  'w.5.name': 'ショットガン', 'w.5.short': 'ショットガン', 'w.5.desc': '5粒の散弾。近いほど強く、離れると威力が落ちる',
  'w.6.name': 'アサルトライフル', 'w.6.short': 'AR', 'w.6.desc': '連射できて射程も長め。どの距離でも戦える万能型',
  'w.7.name': 'バーストライフル', 'w.7.short': 'バースト', 'w.7.desc': '1回で3発。長い射程から、まとめて当てる',
  'w.8.name': 'リボルバー', 'w.8.short': 'リボルバー', 'w.8.desc': '1発が重い5連発。撃ち切るとリロードが長い',
  'w.9.name': 'ライトマシンガン', 'w.9.short': 'LMG', 'w.9.desc': '30発の弾幕。持っている間は動きが少し遅い',
  'w.10.name': 'グレネードランチャー', 'w.10.short': 'グレネード', 'w.10.desc': '放物線で飛んで爆発。段差の上の相手にも届くが、遠くは狙いにくい',
  'w.11.name': 'レールガン', 'w.11.short': 'レールガン', 'w.11.desc': '溜めてから撃つ貫通ビーム。遮蔽物も抜ける',
  'w.12.name': 'ナックル', 'w.12.short': 'ナックル', 'w.12.desc': '拳で殴る。届く距離は短いが、押しっぱなしで連続パンチ',
  'w.13.name': '槍', 'w.13.short': '槍', 'w.13.desc': 'とても長いリーチ。突くまでに少し時間がかかり、突いたあとは隙が大きい',
  'w.14.name': 'ウォーハンマー', 'w.14.short': 'ハンマー', 'w.14.desc': '一撃が重く、当てると相手を吹き飛ばす。振りが遅く、外すと隙だらけ',
  'st.wind': '出の速さ',
  'st.rec': '隙の少なさ',
  'st.instant': 'すぐ',

  'pf.kicker': 'Profile',
  'pf.title': 'プロフィール',
  'pf.name': '名前',
  'pf.namePh': 'プレイヤー名',
  'pf.bio': 'ひとこと',
  'pf.bioPh': 'ひとこと（40文字まで）',
  'pf.titleSec': '称号',
  'pf.bg': '背景',
  'pf.bgNote': 'ティアを獲得するたびに、そのティアの背景が使えるようになります',
  'pf.bgLocked': '{tier}で解放',
  'pf.look': '見た目',
  'look.skin': '肌',
  'look.eyes': '目',
  'look.brows': 'まゆげ',
  'look.hair': '髪',
  'look.nose': '鼻',
  'look.mouth': '口',
  'look.shape': '形',
  'look.color': '色',
  'look.random': 'ランダム',
  'pf.account': 'アカウント',
  'pf.accountNone': '未ログイン（ホームの「Discordでログイン」から）。ログインするとプロフィールがサーバーに保存されます',
  'pf.accountRec': 'オンライン対戦 {w}勝 {l}敗',
  'pf.fid': 'フレンドID',
  'pf.copy': 'コピー',
  'pf.copied': 'コピーしました',
  'sync.saving': 'サーバーに保存中…',
  'sync.saved': 'サーバーに保存済み（どの端末でも同じプロフィール）',
  'sync.error': 'サーバーに保存できませんでした。自動でやり直します',
  'pres.on': 'オンライン',
  'pres.connecting': '接続中…',
  'pres.off': 'オフライン',
  'pf.overall': '総合成績',
  'pf.noGames': 'まだ試合していません',
  'pf.tier': 'ティア',
  'pf.vsCpu': 'CPUレベル別 戦績',
  'pf.wl': '{w}勝 {l}敗',
  'pf.reset': '成績をリセット',
  'pf.resetConfirm': '成績をすべてリセットしますか？（見た目・称号・背景はそのまま残ります）',
  'pf.defaultName': 'プレイヤー',
  'tier.unranked': '未ランク',
  'tier.req0': 'AI対戦でCPUに1勝しよう',
  'tier.req': '{diff}に勝利',
  'tier.reqS': '{diff}にストレート(3-0)で勝利',
  'tier.got': '{req}で獲得',
  'tier.next': '次の {tier} まで：{req}',
  'tier.max': '最高ティアです！',
  'title.rookie': '駆け出しのガンマン',
  'title.regular': '一人前のガンマン',
  'title.bodyguard': '腕利きの用心棒',
  'title.demon_hunter': '鬼狩り',
  'title.godslayer': '鬼神殺し',
  'title.legend': '生ける伝説',
  'title.veteran10': '場数を踏んだ者',
  'title.veteran50': '歴戦の勇士',
  'title.veteran100': '百戦錬磨',
  'title.fall30': '七転び八起き',
  'title.fall100': '不死身の挑戦者',
  'title.debut': '決闘デビュー',
  'title.wanted': '賞金首',
  'title.bounty_hunter': '凄腕の賞金稼ぎ',
  'title.duel_king': '決闘王',
  'title.unbeaten': '百戦百勝',
  'title.partner': '相棒持ち',
  'title.magnificent7': '荒野の七人',
  'title.shadow_blade': '影の刃',
  'title.far_sight': '千里眼',
  'title.point_blank': '至近距離の鬼',
  'title.bomber': '爆弾魔',
  'title.railgun_child': '電磁砲の申し子',
  'title.hive_maker': '蜂の巣職人',
  'title.one_pistol': 'ピストル一丁で十分',
  'title.untouched': '無傷の勝者',
  'title.close_call': '九死に一生',
  'title.unstoppable': '止まらない男',
  'title.precision': '精密射撃',
  'title.pit_drop': '谷落とし',
  'title.wanderer': 'さすらいのガンマン',
  'title.short_sleeper': 'ショートスリーパー',
  'title.first_steps': '初心忘るべからず',
  'title.pioneer': '開拓者',
  'title.rule_breaker': '唯破是律',
  'tcond.rookie': '最初から持っている',
  'tcond.regular': 'CPU「ふつう」に勝つ',
  'tcond.bodyguard': 'CPU「つよい」に勝つ',
  'tcond.demon_hunter': 'CPU「鬼」に勝つ',
  'tcond.godslayer': 'CPU「鬼神」に勝つ',
  'tcond.legend': 'CPU「鬼神」に 3-0 で勝つ',
  'tcond.veteran10': '通算10勝（CPU戦とオンライン対戦の合計）',
  'tcond.veteran50': '通算50勝（CPU戦とオンライン対戦の合計）',
  'tcond.veteran100': '通算100勝（CPU戦とオンライン対戦の合計）',
  'tcond.fall30': '通算30敗',
  'tcond.fall100': '通算100敗',
  'tcond.debut': 'オンライン対戦で初勝利',
  'tcond.wanted': 'オンライン対戦で10勝',
  'tcond.bounty_hunter': 'オンライン対戦で50勝',
  'tcond.duel_king': 'オンライン対戦で100勝',
  'tcond.unbeaten': 'オンライン対戦30戦以上で勝率70%以上',
  'tcond.partner': 'フレンドが1人以上',
  'tcond.magnificent7': 'フレンドが7人以上',
  'tcond.shadow_blade': 'ナイフでとどめを10回',
  'tcond.far_sight': 'スナイパーでとどめを30回',
  'tcond.point_blank': 'ショットガンでとどめを30回',
  'tcond.bomber': 'グレネードでとどめを20回',
  'tcond.railgun_child': 'レールガンでとどめを20回',
  'tcond.hive_maker': 'SMGでとどめを50回',
  'tcond.one_pistol': 'CPU「鬼神」との試合で、とどめを全部ピストルで決めて勝つ',
  'tcond.untouched': 'ダメージを受けずにラウンドに勝つ',
  'tcond.close_call': 'HP 10以下まで追い込まれてから、ラウンドに勝つ',
  'tcond.unstoppable': '5連勝',
  'tcond.precision': '10発以上撃って命中率80%以上で試合に勝つ',
  'tcond.pit_drop': '氷の谷で相手を谷に落として、ラウンドに勝つ',
  'tcond.wanderer': '全6ステージでCPU戦に勝つ',
  'tcond.short_sleeper': '深夜0時〜4時に試合に勝つ',
  'tcond.first_steps': 'CPU「つよい」に勝ったあとで、CPU「よわい」に勝つ',
  'tcond.pioneer': '最初の100人のアカウント（Discordでログイン）',
  'tcond.rule_breaker': '？？？',
  'pf.titleCount': '獲得した称号 {n}',
  'title.got': '称号「{name}」を獲得！',
  'title.gotMany': '称号を{n}つ獲得！ {names}',
  'title.sep': '、',
  'title.trap': 'チートは使えません。そのかわりに称号「唯破是律」をどうぞ。',

  'btn.left': '左',
  'btn.jump': 'ジャンプ',
  'btn.right': '右',
  'btn.attack': '攻撃',
  'btn.duck': 'しゃがむ',
  'btn.reload': 'リロード',
  'btn.heal': '回復',
  'game.aiLevel': 'AI強さ',
  'game.locked': '対戦中は変更不可',
  'game.hint': 'キー設定は「設定」から',
  'game.hintEnter': 'ロビー中に押すと即開始',

  'c.getReady': 'GET READY',
  'c.untilStart': 'ゲーム開始まで',
  'c.pressEnter': 'キーで今すぐ開始',
  'c.stageCpu': 'STAGE  {stage}   ·   CPU  {cpu}',
  'c.weapons': 'あなたの武器  {mine}   ·   CPUの武器  {cpu}',
  'c.you': 'YOU',
  'c.opp': '相手',
  'c.ping': 'PING {n}ms',
  'c.pingOpp': '相手 {n}ms',
  'c.accuracy': '命中率 {p}%    攻撃 {n}回',
  'c.rematchSoon': 'まもなく再戦します',
  'c.rematchWait': '相手の応答を待っています…',
  'c.rematchAsk': '相手が再戦を希望しています',
  'c.toMenu': 'メニューへ',
  'c.again': 'もう一度',
  'c.oppLeft': '相手が退出しました',
  'c.oppLeftWin': '相手が抜けました',
  'c.disconnected': '通信が切断されました',
  'c.tierNext': '次は {tier}：{req}',
  'c.tierMax': '最高ティア到達！',
  'c.discordReported': 'Discordに報告しました'
};

var en = {
  'lang.name': 'English',
  'common.back': 'Back',
  'common.backMenu': 'Back to menu',
  'common.save': 'Save',
  'common.saved': 'Saved',
  'common.reset': 'Reset to default',
  'common.sound': 'Sound on/off',
  'common.settings': 'Settings',
  'common.fullscreen': 'Fullscreen',

  'tos.kicker': 'Terms of Service',
  'tos.title': 'GUN DUEL Terms of Service',
  'tos.h1': 'Prohibited',
  'tos.h1.li1': 'Using cheats, modified clients, aimbots, bots or any other unauthorized programs or tools',
  'tos.h1.li2': 'Intentionally exploiting bugs or vulnerabilities in the game or the server',
  'tos.h1.li3': 'Harassing or disrupting other players',
  'tos.h2': 'If you break the rules',
  'tos.h2.li1': 'Your account and records (profile / tier) may be reset without warning',
  'tos.h2.li2': 'You may be banned from online matches',
  'tos.h2.li3': 'Depending on the violation, a penalty may be applied',
  'tos.h3': 'Other',
  'tos.h3.li1': 'These are simple terms for a fan-made game developed by an individual',
  'tos.h3.li2': 'We cannot guarantee against disconnections or issues caused by server status or your network',
  'tos.h3.li3': 'These terms may change without notice',
  'tos.agree': 'I agree to the terms above',
  'tos.start': 'Agree and start',

  'home.tagline': 'Pick 3 of 14 weapons and win 3 rounds first',
  'home.barHint': 'View and edit your profile',
  'menu.ai': 'VS CPU',
  'menu.ai.sub': 'Runs locally, no lag',
  'menu.loadout': 'Loadout',
  'menu.loadout.sub': 'Bring 3 of 14 weapons',
  'menu.online': 'Online Match',
  'menu.online.sub': 'Play with friends (anti-cheat, low latency)',
  'menu.profile': 'Profile',
  'menu.profile.sub': 'Look, title, background and records',
  'login.discord': 'Log in with Discord',
  'login.logout': 'Log out',
  'login.note': 'Log in to keep your profile on every device and use friends.',
  'login.record': 'Online {w}W {l}L',
  'login.unavailable': 'Login is not available on this server',
  'login.canceled': 'Login canceled',
  'login.stateError': 'Could not verify the login. Please try again.',
  'login.failed': 'Login failed',
  'login.banned': 'This account is banned',
  'login.tooMany': 'Too many attempts. Please wait a moment.',
  'login.noServer': 'Could not connect to the server',

  'stage.kicker': 'Stage Select',
  'stage.title': 'Stage Select',
  'stage.sub': 'Choose your battlefield',
  'stage.no': 'STAGE {n}',
  'stage.backMode': 'Back to modes',
  'stage.classic.name': 'Classic',
  'stage.classic.desc': 'Wooden ledges at every height. Take the high ground and fire down.',
  'stage.classic.theme': 'Moonlit Frontier Town',
  'stage.flat.name': 'Flat',
  'stage.flat.desc': 'Nowhere to hide. A straight duel under the thunder.',
  'stage.flat.theme': 'Storm Plains',
  'stage.tower.name': 'Tower',
  'stage.tower.desc': 'Climb the steel tower. The summit is strong but exposed on every side.',
  'stage.tower.theme': 'Steel Skyline',
  'stage.ruins.name': 'Desert Ruins',
  'stage.ruins.desc': 'Stone pillars stop bullets. Duck, peek and fire back.',
  'stage.ruins.theme': 'Sunset Ruins',
  'stage.glacier.name': 'Glacier Rift',
  'stage.glacier.desc': 'Fall into the rift and you are out. Leap across the floating ice.',
  'stage.glacier.theme': 'Bottomless Rift',
  'stage.temple.name': 'Jungle Temple',
  'stage.temple.desc': 'The steps block bullets, and the summit sees the whole field.',
  'stage.temple.theme': 'Temple in the Jungle',
  'stage.classic.tags': 'Many platforms,Height',
  'stage.flat.tags': 'No platforms,Ground fight',
  'stage.tower.tags': 'Central tower,High ground',
  'stage.ruins.tags': 'Cover,Peek and shoot',
  'stage.glacier.tags': 'Pitfall,Jumps',
  'stage.temple.tags': 'Steps,King of the hill',
  'stage.go': 'Fight here',
  'stage.count': '{n} / {total}',
  'stage.keys': '← → to switch    Enter to select',
  'stage.new': 'NEW',
  'vs.winrate': 'WIN {p}%',
  'vs.record': '{w}W {l}L',
  'vs.online': 'ONLINE',
  'vs.cpu': 'VS CPU',
  'vs.noRecord': 'No record',
  'vs.discord': 'Discord ✓ {name}',
  'menu.friends': 'Friends',
  'menu.friends.sub': 'Friend ID, requests and match invites',
  'fr.kicker': 'Friends',
  'fr.title': 'Friends',
  'fr.needLogin': 'Log in with Discord to use friends.',
  'fr.myId': 'Your friend ID',
  'fr.addTitle': 'Add a friend',
  'fr.addPh': "Friend's ID (8 characters)",
  'fr.add': 'Send request',
  'fr.incoming': 'Requests ({n})',
  'fr.outgoing': 'Sent requests',
  'fr.list': 'Friends ({on} online / {n})',
  'fr.none': 'No friends yet. Share your friend ID and send a request.',
  'fr.accept': 'Accept',
  'fr.decline': 'Decline',
  'fr.cancel': 'Cancel',
  'fr.waiting': 'Pending',
  'fr.invite': 'Invite',
  'fr.remove': 'Remove friend',
  'fr.removeConfirm': 'Remove {name} from your friends?',
  'fr.close': 'Close',
  'fr.r.sent': 'Request sent. You will be friends once they accept.',
  'fr.r.accepted': 'You and {name} are now friends',
  'fr.r.already': 'You are already friends',
  'fr.r.pending': 'Request already sent',
  'fr.r.self': 'That is your own ID',
  'fr.r.limit': 'Friend limit (100) reached',
  'fr.r.full': 'Too many pending requests. Please try later.',
  'fr.r.not_found': 'No player with that ID',
  'fr.r.bad': 'Friend IDs are 8 letters and numbers',
  'fr.r.error': 'Could not reach the server. Please try again.',
  'fr.r.too_many': 'Too many actions. Please wait a moment.',
  'fr.r.ok': 'Done',
  'fr.gotRequest': '{name} sent you a friend request',
  'fr.notConnected': 'Not connected to the server. Please wait a moment.',
  'fst.online': 'Online',
  'fst.cpu': 'Playing vs CPU',
  'fst.match': 'In a match',
  'fst.offline': 'Offline',
  'fst.offAgo': 'Offline · {ago}',
  'ago.now': 'just now',
  'ago.min': '{n} min ago',
  'ago.hour': '{n} h ago',
  'ago.day': '{n} d ago',
  'fm.tier': 'Tier',
  'fm.online': 'Online record',
  'fm.cpu': 'CPU record',
  'fm.discord': 'Discord',
  'fm.rec': '{w}W {l}L · {p}%',
  'fm.noRec': 'No record',
  'inv.title': 'Match invite',
  'inv.msg': 'invited you to a match',
  'inv.join': 'Join',
  'inv.no': 'Decline',
  'inv.creating': 'Creating a room to invite {name}…',
  'inv.sending': 'Sending an invite to {name}…',
  'inv.sent': 'Invite sent to {name}. Waiting for a reply…',
  'inv.sentCpu': '{name} is playing vs CPU and will see the invite after the match…',
  'inv.accepted': '{name} is joining!',
  'inv.declined': '{name} declined',
  'inv.noAnswer': 'No reply from {name}',
  'inv.canceled': "{name}'s invite was canceled",
  'inv.fail.not_friend': 'You can only invite friends',
  'inv.fail.offline': '{name} is offline',
  'inv.fail.busy': '{name} is in a match',
  'inv.fail.no_room': 'Could not create the room. Please try again.',
  'inv.fail.too_many': 'Too many invites. Please wait a moment.',
  'bot.notFound': 'No player named "{q}" was found. Search by in-game name, Discord name or friend ID (8 characters). Only players who have logged in with Discord can be found.',
  'bot.many': '{n} players match "{q}". Please use their friend ID:',
  'bot.tier': 'Tier',
  'bot.title': 'Title',
  'bot.status': 'Status',
  'bot.online': 'Online record',
  'bot.cpu': 'CPU record',
  'bot.fid': 'Friend ID',
  'bot.rec': '{p}% win rate ({w}W {l}L)',
  'bot.noRec': 'None yet',
  'bot.lastSeen': 'Last seen {t}',

  'cpu.kicker': 'CPU Level',
  'cpu.title': 'Choose CPU Level',
  'cpu.sub': 'Every level moves, jumps and reloads exactly like you. Only the speed and accuracy of decisions differ.',
  'cpu.stage': 'Stage: {name}',
  'cpu.weapons': 'Weapons: {list}',
  'cpu.change': 'Change weapons',
  'cpu.backStage': 'Back to stages',
  'cpu.desc.easy': 'Slow decisions, same movement',
  'cpu.desc.normal': 'Reacts quickly and dodges well',
  'cpu.desc.hard': 'Keeps its distance while trading shots',
  'cpu.desc.pro': 'Hides, dodges and punishes mistakes',
  'cpu.desc.god': 'Inhuman reactions and decisions',
  'diff.easy': 'Easy',
  'diff.normal': 'Normal',
  'diff.hard': 'Hard',
  'diff.pro': 'Expert',
  'diff.god': 'Legend',

  'room.kicker': 'Online Match',
  'room.title': 'Online Match',
  'room.host': 'Create a room',
  'room.create': 'Create a room and show its number',
  'room.guest': 'Join a room',
  'room.placeholder': 'Enter the 6-digit room number',
  'room.join': 'Join',
  'room.connecting': 'Connecting to the server...',
  'room.waiting': 'Waiting for your opponent...',
  'room.joined': 'Connected!',
  'room.connectFail': 'Connection failed. Check the server URL.',
  'room.need6': 'Please enter a 6-digit number',
  'room.oldServer': 'The server is outdated. Please update the server files too.',
  'room.error': 'Error: {msg}',
  'err.login_required': 'You need to log in with Discord to play online',
  'err.server_busy': 'The server is busy. Please try again shortly.',
  'err.too_many_rooms': 'You have too many rooms open',
  'err.too_many_fails': 'Too many wrong room numbers. Please wait a moment.',
  'err.room_not_found': 'Room not found. Check the number.',
  'err.same_account': 'You can\'t play against your own account',
  'err.room_full': 'This room is already in a match',
  'err.room_timeout': 'The room was closed because nobody joined',
  'err.reload': 'The game was updated. Please reload the page.',

  'set.kicker': 'Settings',
  'set.title': 'Settings',
  'set.sound': 'Sound',
  'set.bgm': 'Music',
  'set.se': 'Sound effects',
  'set.lang': 'Language',
  'set.keys': 'Key bindings',
  'set.server': 'Server',
  'set.serverNote': 'Leave this as is unless you run your own server.',
  'kb.left': 'Move left',
  'kb.right': 'Move right',
  'kb.jump': 'Jump',
  'kb.duck': 'Duck',
  'kb.attack': 'Attack (hold to keep firing)',
  'kb.reload': 'Reload',
  'kb.w1': 'Weapon slot 1',
  'kb.w2': 'Weapon slot 2',
  'kb.w3': 'Weapon slot 3',
  'kb.heal': 'Heal (once per round)',
  'kb.waiting': 'Press a key...',
  'kb.unset': 'Unset',
  'key.mouse0': 'Left click',
  'key.mouse1': 'Middle click',
  'key.mouse2': 'Right click',

  'lo.kicker': 'Loadout',
  'lo.title': 'Loadout',
  'lo.sub': 'Choose 3 weapons to bring. Switch with keys 1, 2 and 3 during a match.',
  'lo.hint': 'Pick a slot, then tap a weapon (equipped weapons swap places)',
  'lo.slot': 'SLOT {n}',
  'lo.start': 'START',
  'lo.done': 'Done',
  'st.range': 'Range',
  'st.power': 'Damage',
  'st.rate': 'Fire rate',
  'st.mag': 'Ammo',
  'st.reload': 'Reload',
  'st.perSec': '{n}/s',
  'st.sec': '{n}s',
  'st.none': 'none',
  'st.approx': '~{n}',

  'w.1.name': 'Knife', 'w.1.short': 'KNIFE', 'w.1.desc': 'Slash up close. Hits hard, but its reach is very short.',
  'w.2.name': 'Pistol', 'w.2.short': 'PISTOL', 'w.2.desc': 'The basic sidearm. One shot, then a short reload.',
  'w.3.name': 'Sniper', 'w.3.short': 'SNIPER', 'w.3.desc': 'Fast bullets with long range. A long reload after every shot.',
  'w.4.name': 'SMG', 'w.4.short': 'SMG', 'w.4.desc': 'Hold to spray fast. Best at close range.',
  'w.5.name': 'Shotgun', 'w.5.short': 'SHOTGUN', 'w.5.desc': 'Fires 5 pellets. Strong up close, weaker at range.',
  'w.6.name': 'Assault Rifle', 'w.6.short': 'AR', 'w.6.desc': 'Automatic with good range. Works at any distance.',
  'w.7.name': 'Burst Rifle', 'w.7.short': 'BURST', 'w.7.desc': 'Three rounds per pull. Lands grouped hits from far away.',
  'w.8.name': 'Revolver', 'w.8.short': 'REVOLVER', 'w.8.desc': 'Five heavy rounds. A long reload once empty.',
  'w.9.name': 'Light Machine Gun', 'w.9.short': 'LMG', 'w.9.desc': 'A 30-round barrage. You move a bit slower while holding it.',
  'w.10.name': 'Grenade Launcher', 'w.10.short': 'LAUNCHER', 'w.10.desc': 'Lobs explosive rounds in an arc. Reaches enemies on ledges, but hard to aim far away.',
  'w.11.name': 'Railgun', 'w.11.short': 'RAILGUN', 'w.11.desc': 'Charge, then fire a piercing beam that goes through cover.',
  'w.12.name': 'Knuckles', 'w.12.short': 'KNUCKLE', 'w.12.desc': 'Short reach, but hold the button for rapid punches.',
  'w.13.name': 'Spear', 'w.13.short': 'SPEAR', 'w.13.desc': 'Very long reach. Slow to thrust and leaves you open afterwards.',
  'w.14.name': 'War Hammer', 'w.14.short': 'HAMMER', 'w.14.desc': 'A heavy blow that knocks the enemy flying. Slow swing; miss and you are wide open.',
  'st.wind': 'Startup',
  'st.rec': 'Recovery',
  'st.instant': 'Instant',

  'pf.kicker': 'Profile',
  'pf.title': 'Profile',
  'pf.name': 'Name',
  'pf.namePh': 'Player name',
  'pf.bio': 'Bio',
  'pf.bioPh': 'Say something (40 characters max)',
  'pf.titleSec': 'Title',
  'pf.bg': 'Background',
  'pf.bgNote': 'Each tier you earn unlocks a background in that tier\'s color',
  'pf.bgLocked': 'Unlocks at {tier}',
  'pf.look': 'Appearance',
  'look.skin': 'Skin',
  'look.eyes': 'Eyes',
  'look.brows': 'Eyebrows',
  'look.hair': 'Hair',
  'look.nose': 'Nose',
  'look.mouth': 'Mouth',
  'look.shape': 'Shape',
  'look.color': 'Color',
  'look.random': 'Random',
  'pf.account': 'Account',
  'pf.accountNone': 'Not logged in (use "Log in with Discord" on the home screen). Log in to save your profile on the server',
  'pf.accountRec': 'Online {w}W {l}L',
  'pf.fid': 'Friend ID',
  'pf.copy': 'Copy',
  'pf.copied': 'Copied!',
  'sync.saving': 'Saving to server…',
  'sync.saved': 'Saved to server (same profile on every device)',
  'sync.error': 'Could not save to server. Retrying automatically',
  'pres.on': 'Online',
  'pres.connecting': 'Connecting…',
  'pres.off': 'Offline',
  'pf.overall': 'Overall',
  'pf.noGames': 'No matches yet',
  'pf.tier': 'Tier',
  'pf.vsCpu': 'Record by CPU level',
  'pf.wl': '{w}W {l}L',
  'pf.reset': 'Reset records',
  'pf.resetConfirm': 'Reset all records? (Your appearance, title and backgrounds are kept.)',
  'pf.defaultName': 'Player',
  'tier.unranked': 'UNRANKED',
  'tier.req0': 'Win a match against the CPU',
  'tier.req': 'Beat {diff}',
  'tier.reqS': 'Beat {diff} 3-0',
  'tier.got': 'Earned by: {req}',
  'tier.next': 'Next {tier}: {req}',
  'tier.max': 'You are at the top tier!',
  'title.rookie': 'Rookie Gunslinger',
  'title.regular': 'Seasoned Gunslinger',
  'title.bodyguard': 'Hired Gun',
  'title.demon_hunter': 'Demon Hunter',
  'title.godslayer': 'Godslayer',
  'title.legend': 'Living Legend',
  'title.veteran10': 'Battle-Tested',
  'title.veteran50': 'War Veteran',
  'title.veteran100': 'Hardened by a Hundred Fights',
  'title.fall30': 'Down Seven, Up Eight',
  'title.fall100': 'Undying Challenger',
  'title.debut': 'Duel Debut',
  'title.wanted': 'Wanted',
  'title.bounty_hunter': 'Bounty Hunter',
  'title.duel_king': 'Duel King',
  'title.unbeaten': 'Ever Victorious',
  'title.partner': 'Got a Partner',
  'title.magnificent7': 'The Magnificent Seven',
  'title.shadow_blade': 'Shadow Blade',
  'title.far_sight': 'Far Sight',
  'title.point_blank': 'Point-Blank Fiend',
  'title.bomber': 'Mad Bomber',
  'title.railgun_child': 'Child of the Railgun',
  'title.hive_maker': 'Swiss Cheese Maker',
  'title.one_pistol': 'One Pistol Is Enough',
  'title.untouched': 'Untouched',
  'title.close_call': 'Close Call',
  'title.unstoppable': 'Unstoppable',
  'title.precision': 'Precision Shot',
  'title.pit_drop': 'Into the Abyss',
  'title.wanderer': 'Wandering Gunslinger',
  'title.short_sleeper': 'Short Sleeper',
  'title.first_steps': 'Never Forget Your Roots',
  'title.pioneer': 'Pioneer',
  'title.rule_breaker': 'Rulebreaker',
  'tcond.rookie': 'Everyone starts with this',
  'tcond.regular': 'Beat the Normal CPU',
  'tcond.bodyguard': 'Beat the Hard CPU',
  'tcond.demon_hunter': 'Beat the Expert CPU',
  'tcond.godslayer': 'Beat the Legend CPU',
  'tcond.legend': 'Beat the Legend CPU 3-0',
  'tcond.veteran10': '10 total wins (CPU + online)',
  'tcond.veteran50': '50 total wins (CPU + online)',
  'tcond.veteran100': '100 total wins (CPU + online)',
  'tcond.fall30': '30 total losses',
  'tcond.fall100': '100 total losses',
  'tcond.debut': 'Win your first online match',
  'tcond.wanted': '10 online wins',
  'tcond.bounty_hunter': '50 online wins',
  'tcond.duel_king': '100 online wins',
  'tcond.unbeaten': '70%+ win rate over 30+ online matches',
  'tcond.partner': 'Have at least 1 friend',
  'tcond.magnificent7': 'Have at least 7 friends',
  'tcond.shadow_blade': 'Finish 10 opponents with the knife',
  'tcond.far_sight': 'Finish 30 opponents with the sniper',
  'tcond.point_blank': 'Finish 30 opponents with the shotgun',
  'tcond.bomber': 'Finish 20 opponents with grenades',
  'tcond.railgun_child': 'Finish 20 opponents with the railgun',
  'tcond.hive_maker': 'Finish 50 opponents with the SMG',
  'tcond.one_pistol': 'Beat the Legend CPU with every finishing blow from the pistol',
  'tcond.untouched': 'Win a round without taking damage',
  'tcond.close_call': 'Win a round after dropping to 10 HP or less',
  'tcond.unstoppable': 'Win 5 matches in a row',
  'tcond.precision': 'Win a match with 80%+ accuracy (10+ shots)',
  'tcond.pit_drop': 'Win a round on Glacier Rift by knocking your opponent into the pit',
  'tcond.wanderer': 'Beat the CPU on all 6 stages',
  'tcond.short_sleeper': 'Win a match between midnight and 4 AM',
  'tcond.first_steps': 'Beat the Easy CPU after you have beaten the Hard CPU',
  'tcond.pioneer': 'One of the first 100 accounts (log in with Discord)',
  'tcond.rule_breaker': '???',
  'pf.titleCount': 'Titles earned: {n}',
  'title.got': 'New title: {name}!',
  'title.gotMany': '{n} new titles! {names}',
  'title.sep': ', ',
  'title.trap': 'Cheats do not work here. Enjoy the title "Rulebreaker" instead.',

  'btn.left': 'Left',
  'btn.jump': 'Jump',
  'btn.right': 'Right',
  'btn.attack': 'Attack',
  'btn.duck': 'Duck',
  'btn.reload': 'Reload',
  'btn.heal': 'Heal',
  'game.aiLevel': 'CPU level',
  'game.locked': 'Locked during a match',
  'game.hint': 'Change keys in Settings',
  'game.hintEnter': 'Press in the lobby to start now',

  'c.getReady': 'GET READY',
  'c.untilStart': 'Match starts in',
  'c.pressEnter': 'to start now',
  'c.stageCpu': 'STAGE  {stage}   ·   CPU  {cpu}',
  'c.weapons': 'YOU  {mine}   ·   CPU  {cpu}',
  'c.you': 'YOU',
  'c.opp': 'Opponent',
  'c.ping': 'PING {n}ms',
  'c.pingOpp': 'OPP {n}ms',
  'c.accuracy': 'Accuracy {p}%    Attacks {n}',
  'c.rematchSoon': 'Rematch starting',
  'c.rematchWait': 'Waiting for your opponent…',
  'c.rematchAsk': 'Your opponent wants a rematch',
  'c.toMenu': 'Menu',
  'c.again': 'Again',
  'c.oppLeft': 'Your opponent left',
  'c.oppLeftWin': 'Your opponent left',
  'c.disconnected': 'Disconnected',
  'c.tierNext': 'Next: {tier} — {req}',
  'c.tierMax': 'Top tier reached!',
  'c.discordReported': 'Posted to Discord'
};

root.GunDuelLang = { ja: ja, en: en };
})(typeof self !== 'undefined' ? self : this);
